Fix a bug that image cannot be converted correctly
future-standard/scorer-cloud-processing-python pull request #1
Opened 2019-11-05 10:56 UTC by sasakisasaki

@mikilabo レビューをお願いいたします

2019-11-11 06:22 UTC, mikilabo approved these changes

2019-11-11 06:28 UTC, kounoike commented
バグ修正でpublic interfaceを修正してはいけません。
self.dataを新設していること、オブジェクト作成直後のself.imageの振る舞いが変わっています。

2019-11-12 02:59 UTC, sasakisasaki commented
@kounoike こちら修正しましたので、お手すきの際にレビューをお願いします

2019-11-14 09:04 UTC, kounoike requested changes

2019-11-14 09:04 UTC, kounoike commented on scorer/scorer_sdk.py
> +            self.image = np.frombuffer(data, dtype=np.uint8).reshape((self.my_row[0],self.my_col[0], 1));
I420のときにshapeが(h, w)から(h, w, 1)に変わってると思うけど？

2019-11-14 09:04 UTC, kounoike commented on scorer/scorer_sdk.py
> +        else:
できればimage_format=="RGB"の場合も入れておいて欲しい

2019-11-14 10:40 UTC, sasakisasaki commented on scorer/scorer_sdk.py
> +            self.image = np.frombuffer(data, dtype=np.uint8).reshape((self.my_row[0],self.my_col[0], 1));
対応いたしました

2019-11-14 10:40 UTC, sasakisasaki commented on scorer/scorer_sdk.py
> +        else:
対応いたしました

2019-11-14 10:40 UTC, sasakisasaki commented
@kounoike コメントをくださいましてありがとうございました。再度レビューをお願いします

2019-11-14 11:08 UTC, kounoike approved these changes

2019-11-14 11:10 UTC, merged